name: nostrface
description: "A Tinder-like profile browser for Nostr"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State management
  flutter_riverpod: ^2.3.6
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Secure storage for keys
  flutter_secure_storage: ^8.0.0
  # HTTP requests
  http: ^1.1.0
  # Websocket for Nostr relay connections
  web_socket_channel: ^2.4.0
  # JSON serialization
  json_annotation: ^4.8.1
  # Routing
  go_router: ^10.0.0
  # UI components
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  # Utilities
  equatable: ^2.0.5
  uuid: ^3.0.7
  crypto: ^3.0.3
  # Nostr protocol implementation
  nostr: ^1.4.3
  # Bech32 encoding/decoding for nprofile support
  bech32: ^0.2.2
  # Image loading and caching
  cached_network_image: ^3.2.3
  # Card swiping
  card_swiper: ^3.0.1
  # Reactive forms
  reactive_forms: ^16.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
