include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_print: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    avoid_web_libraries_in_flutter: true
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    throw_in_finally: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    valid_regexps: true

    # Style rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_null_checks_in_equality_operators: true
    avoid_return_types_on_setters: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: true
    library_names: true
    library_prefixes: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
